"""remove extracted_text from documents

Revision ID: 7ad5deae0c4f
Revises: 4263b966ad07
Create Date: 2026-06-15 19:38:53.873728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ad5deae0c4f'
down_revision: Union[str, Sequence[str], None] = '4263b966ad07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extracted_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extracted_text', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
